export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SAVE_PROPERTY_SEARCH = 'SAVE_PROPERTY_SEARCH';
export const INVALID_PROPERTY_SEARCH = 'INVALID_PROPERTY_SEARCH';
export const START_FETCHING_PROPERTY_DATA = 'START_FETCHING_PROPERTY_DATA';
