module.exports = function otaMappings() {
    return [
        { id: 63, name: 'GoMMT' },
        { id: 3, name: 'Expedia' },
        { id: 75, name: 'RateGain' },
        { id: 5, name: 'Booking.com' },
        { id: 66, name: 'Tiket.com' },
        { id: 62, name: 'Pegipegi' },
        { id: 70, name: 'Mister Aladin' },
        { id: 76, name: 'Mg Holiday' },
        { id: 2, name: 'Agoda' },
        { id: 41, name: 'Hotel Beds' },
        { id: 74, name: 'HotelTonight' },
        { id: 24, name: 'TraveLoka' },
        { id: 2001, name: 'AXIS' },
        { id: 18, name: 'GoIbibo' },
        { id: 10001, name: 'Default_OTA' },
        { id: 272, name: 'Ctrip' },
        { id: 6, name: 'MakeMyTrip' },
        { id: 60, name: 'Elong' },
        { id: 59, name: 'Yun Zhang Gui' },
        { id: 58, name: 'JL Tours' },
        { id: 32, name: 'Qunar' },
        { id: 55, name: 'Meituan' },
        { id: 54, name: 'Fliggy.com' },
        { id: 271, name: 'Airbnb' },
        { id: 3001, name: 'TL - Lincoln' },
        { id: 100, name: 'Rakuten' },
        { id: 101, name: 'Jalan' },
        { id: 27, name: 'Escapada Rural' },
        { id: 1305, name: 'Traveloka_Direct' },
        { id: 9000, name: 'Manual_Jalan' },
        { id: 8, name: 'Homeaway' },
        { id: 9001, name: 'Manual_Rakuten' },
        { id: 9, name: 'Synxis' }
    ];
};
